import{a as y,S as b,i as n}from"./assets/vendor-bac76ac5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const s={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),more:document.querySelector(".load-more"),guard:document.querySelector(".js-guard")};y.defaults.baseURL="https://pixabay.com/api/";const L="44676438-8f15550b2268961ea3e6a8228",p=async(e,t=1,a)=>{if(e){const{data:i}=await y({method:"GET",params:{key:L,image_type:"photo",orientation:"horizontal",safesearch:!0,q:e,per_page:a,page:t}});return i}},v=e=>e.map(({largeImageURL:t,webformatURL:a,tags:i,likes:r,views:o,comments:c,downloads:h})=>`      
        <a href="${t}" class="item">
        <img src="${a}" alt="${i}" loading="lazy" />
        <div class="info">
            <p class="info-item"><b>Likes</b>${r}</p>
            <p class="info-item"><b>Views</b>${o}</p>
            <p class="info-item"><b>Comments</b>${c}</p>
            <p class="info-item"><b>Downloads</b>${h}</p>
        </div>
        </a>`).join(""),m=e=>e.classList.remove("visually-hidden"),d=e=>e.classList.add("visually-hidden");let u="",l=1,f=40;const E=new b(".gallery a",{captionsData:"alt",captionDelay:250}),S=async e=>{e.preventDefault(),s.gallery.innerHTML="",d(s.more),m(s.loader);const t=e.target.elements.searchQuery.value.trim().toLowerCase();if(t===""){n.error({title:"Error",message:"Please enter a search query"}),d(s.loader);return}u=t,l=1;try{const{totalHits:a,hits:i}=await p(u,l,f);a&&n.info({message:`Hooray! We found ${a} images`}),g(i,a)}catch(a){n.error({title:"Error",message:a.message})}finally{d(s.loader)}},q=async()=>{l+=1,m(s.loader);try{const{totalHits:e,hits:t}=await p(u,l,f);g(t,e)}catch(e){n.error({title:"Error",message:e.message})}finally{d(s.loader)}};function g(e,t){if(d(s.more),e.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again."});return}s.gallery.insertAdjacentHTML("beforeend",v(e)),E.refresh(),l*f>=t?l>1&&n.info({message:"We're sorry, but you've reached the end of search results"}):m(s.more)}s.form.addEventListener("submit",S);s.more.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
